import asyncio
import json
import sys

import websockets


SCREENING_ID = None

# Change these two paths to your actual synthetic demo files.
DOCUMENT_PATH = r"E:\border-screening\backend\demo_document.jpg"
VERIFICATION_PATH = r"E:\border-screening\backend\demo_face.jpg"


async def run_test():

    print("Starting real screening test...\n")

    # ------------------------------------------------------
    # IMPORTANT
    # ------------------------------------------------------
    # The screening ID is generated by the API.
    #
    # We therefore need to create the screening ID before
    # the API call in order to connect to the WebSocket.
    #
    # For this test we generate one here and pass it through
    # the screening API.
    # ------------------------------------------------------

    import uuid

    screening_id = str(uuid.uuid4())

    print(
        f"Screening ID: {screening_id}\n"
    )

    ws_uri = (
        "ws://127.0.0.1:8000"
        f"/api/ws/screenings/{screening_id}"
    )

    print(
        f"Connecting to:\n{ws_uri}\n"
    )

    async with websockets.connect(
        ws_uri
    ) as websocket:

        # --------------------------------------------------
        # Connection message
        # --------------------------------------------------

        message = await websocket.recv()

        connection_data = json.loads(
            message
        )

        print(
            "WebSocket:",
            connection_data
        )

        # --------------------------------------------------
        # Start real screening
        # --------------------------------------------------

        print(
            "\nStarting screening pipeline...\n"
        )

        # We cannot easily send multipart data with the
        # websocket itself, so the HTTP screening request
        # is started using aiohttp.
        #
        # Install it if needed:
        #
        # python -m pip install aiohttp
        #

        import aiohttp

        form = aiohttp.FormData()

        form.add_field(
            "document_image",
            open(
                DOCUMENT_PATH,
                "rb"
            ),
            filename="demo_document.jpg",
            content_type="image/jpeg",
        )

        form.add_field(
            "verification_image",
            open(
                VERIFICATION_PATH,
                "rb"
            ),
            filename="demo_face.jpg",
            content_type="image/jpeg",
        )

        # --------------------------------------------------
        # Authentication
        # --------------------------------------------------
        #
        # Replace this with the JWT token from your login
        # API if your screening endpoint requires auth.
        #
        # The endpoint currently requires authentication.
        #

        TOKEN = "YOUR_JWT_TOKEN_HERE"

        headers = {
            "Authorization": f"Bearer {TOKEN}"
        }

        async with aiohttp.ClientSession(
            headers=headers
        ) as session:

            screening_task = asyncio.create_task(
                session.post(
                    "http://127.0.0.1:8000/api/screenings",
                    data=form,
                )
            )

            # --------------------------------------------------
            # Receive real-time screening events
            # --------------------------------------------------

            while True:

                message = await websocket.recv()

                data = json.loads(
                    message
                )

                if data.get("type") != "screening_progress":
                    continue

                print(
                    f"[{data['progress']:3}%] "
                    f"{data['stage']} "
                    f"-> {data['status']}"
                )

                if data["progress"] >= 100:
                    break

            # --------------------------------------------------
            # Get HTTP screening result
            # --------------------------------------------------

            response = await screening_task

            response_text = await response.text()

            print(
                "\nHTTP status:",
                response.status
            )

            print(
                "\nScreening result:"
            )

            try:
                print(
                    json.dumps(
                        json.loads(
                            response_text
                        ),
                        indent=2,
                    )
                )

            except json.JSONDecodeError:
                print(
                    response_text
                )


if __name__ == "__main__":

    try:
        asyncio.run(
            run_test()
        )

    except KeyboardInterrupt:

        print(
            "\nTest cancelled."
        )

    except Exception as error:

        print(
            "\nTEST FAILED:"
        )

        print(
            repr(error)
        )

        sys.exit(1)