export const statusTypes = {
  LOW: 'success',
  CLEARED: 'success',
  VALID: 'success',
  ONLINE: 'success',
  PASSED: 'success',
  ACTIVE: 'success',
  COMPLETED: 'success',
  OPERATIONAL: 'success',
  MEDIUM: 'warning',
  WARNING: 'warning',
  ELEVATED: 'warning',
  REVIEW: 'warning',
  'REVIEW REQUIRED': 'warning',
  HIGH: 'danger',
  CRITICAL: 'danger',
  FAILED: 'danger',
  'FAILED/ANOMALY': 'danger',
  'ANOMALY DETECTED': 'danger',
  ALERT: 'danger',
  'IN PROGRESS': 'info',
  INFO: 'info',
  WAITING: 'neutral',
  PENDING: 'neutral',
  OFFLINE: 'neutral',
  DISABLED: 'neutral',
  INACTIVE: 'neutral',
};
