import Card from '../../../components/ui/Card';
import RiskScorePanel from '../../../components/data-display/RiskScorePanel';

export default function ResultRiskAssessment({ result }) {
  const score = Number(result?.score ?? 0);
  const level = String(result?.level || 'UNKNOWN').toUpperCase();
  const explanation =
    result?.explanation ||
    'The risk engine completed the screening assessment without additional explanation.';

  return (
    <Card aria-labelledby="result-risk-title">
      <h2
        id="result-risk-title"
        className="mb-4 text-section font-semibold text-navy"
      >
        Risk Assessment
      </h2>

      <RiskScorePanel
        score={score}
        level={level}
      />

      <div className="mt-4 border-t border-default pt-4">
        <h3 className="text-card font-semibold text-navy">
          Why this result?
        </h3>

        <p className="mt-2 text-body">
          {explanation}
        </p>
      </div>

      <div className="mt-4 border-t border-default pt-4">
        <h3 className="text-card font-semibold text-navy">
          System Recommendation
        </h3>

        <p className="mt-2 text-body">
          {result?.recommendation ||
            'The backend risk engine has completed its assessment. Final action remains with the authorized officer.'}
        </p>
      </div>

      <p className="mt-4 text-caption text-muted">
        Prototype: risk scoring is generated by the configured backend risk
        engine using synthetic test data. Results are for demonstration and
        are not used for real-world border decisions.
      </p>
    </Card>
  );
}