import { useId } from 'react';
import Card from '../../../components/ui/Card';
import StatusBadge from '../../../components/ui/StatusBadge';

export default function ResultEvidenceSection({
  title,
  checks = [],
  status,
  explanation,
}) {
  const titleId = useId();

  return (
    <Card aria-labelledby={titleId}>
      <div className="mb-4 flex flex-wrap justify-between gap-2">
        <h2 id={titleId} className="text-section font-semibold text-navy">
          {title}
        </h2>

        {status && (
          <StatusBadge status={status}>
            {status}
          </StatusBadge>
        )}
      </div>

      {explanation && (
        <p className="mb-4 text-body text-muted">
          {explanation}
        </p>
      )}

      {checks.length > 0 ? (
        <dl className="grid gap-x-5 gap-y-4 text-body sm:grid-cols-2">
          {checks.map((check, index) => {
            // Backend-generated checks may not contain an `id`.
            // Use a stable fallback key to avoid React key warnings.
            const checkKey =
              check.id ||
              `${title}-${check.label || 'check'}-${index}`;

            return (
              <div
                key={checkKey}
                className="flex min-w-0 flex-wrap items-start justify-between gap-2 border-b border-default pb-3"
              >
                <dt className="font-medium">
                  {check.label || 'Validation Check'}
                </dt>

                <dd>
                  <StatusBadge
                    status={check.status || 'UNKNOWN'}
                    variant={check.variant}
                  >
                    {check.status || 'UNKNOWN'}
                  </StatusBadge>
                </dd>

                {check.explanation && (
                  <dd className="w-full text-caption text-muted">
                    {check.explanation}
                  </dd>
                )}
              </div>
            );
          })}
        </dl>
      ) : (
        <p className="text-body text-muted">
          No findings available for this analysis.
        </p>
      )}

      <p className="mt-3 text-caption text-muted">
        Screening findings generated by the BorderGuard AI analysis pipeline.
      </p>
    </Card>
  );
}