import { useId } from 'react';
import Card from '../../../components/ui/Card';

export default function RiskFactorList({ factors = [], total = 0 }) {
  const titleId = useId();

  const normalizedTotal = Number(total ?? 0);

  return (
    <Card aria-labelledby={titleId}>
      <h2
        id={titleId}
        className="text-section font-semibold text-navy"
      >
        Risk Factors
      </h2>

      <p className="mt-2 text-caption text-muted">
        Risk factors identified by the configured backend risk engine.
      </p>

      {factors.length > 0 ? (
        <dl className="mt-3 divide-y divide-default">
          {factors.map((factor, index) => {
            const points = Number(factor?.points ?? 0);
            const label =
              factor?.label || `Risk factor ${index + 1}`;

            return (
              <div
                key={`${label}-${index}`}
                className="flex flex-wrap items-start justify-between gap-2 py-3 text-body"
              >
                <dt className="font-medium">
                  {label}
                </dt>

                <dd className="font-semibold tabular-nums">
                  {points > 0 ? `+${points}` : points}
                </dd>

                {factor?.explanation && (
                  <dd className="w-full text-caption text-muted">
                    {factor.explanation}
                  </dd>
                )}
              </div>
            );
          })}
        </dl>
      ) : (
        <p className="mt-3 text-body text-muted">
          No risk factors were returned by the backend risk engine.
        </p>
      )}

      <div className="mt-2 flex justify-between gap-3 border-t border-default pt-3 text-body font-semibold">
        <span>Total</span>

        <span className="tabular-nums">
          {normalizedTotal} / 100
        </span>
      </div>

      <p className="mt-3 text-caption text-muted">
        Risk score is generated by the backend assessment pipeline using
        synthetic test data. Final decisions remain with the authorized
        officer.
      </p>
    </Card>
  );
}